# Generated by Django 4.2.7 on 2024-02-04 07:36

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='availableCab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabID', models.TextField(max_length=10)),
                ('cabModel', models.TextField(max_length=10)),
                ('cabCapacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BookingDetails',
            fields=[
                ('bookingID', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('car_model', models.TextField(max_length=20)),
                ('start_location', models.TextField(max_length=50)),
                ('end_location', models.TextField(max_length=50)),
                ('booking_time', models.DateTimeField(default=datetime.datetime(2024, 2, 4, 13, 6, 41, 829720))),
                ('booking_fare', models.IntegerField()),
            ],
        ),
    ]
