# Generated by Django 4.2.7 on 2024-02-04 11:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cab_booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='carsAvailable',
            fields=[
                ('carID', models.IntegerField(primary_key=True, serialize=False)),
                ('carModel', models.TextField(max_length=30)),
                ('carCapacity', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='availablecab',
            old_name='cabCapacity',
            new_name='availableCapacity',
        ),
        migrations.RenameField(
            model_name='availablecab',
            old_name='cabModel',
            new_name='carModel',
        ),
        migrations.RemoveField(
            model_name='availablecab',
            name='cabID',
        ),
        migrations.RemoveField(
            model_name='bookingdetails',
            name='car_model',
        ),
        migrations.AddField(
            model_name='availablecab',
            name='carID',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookingdetails',
            name='carID',
            field=models.IntegerField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='bookingdetails',
            name='booking_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 4, 16, 29, 32, 121737)),
        ),
    ]
