# Generated by Django 4.2.7 on 2024-02-04 11:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cab_booking', '0003_bookingdetails_trip_date_bookingdetails_userid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdetails',
            name='booking_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 4, 17, 20, 50, 848719)),
        ),
        migrations.AlterField(
            model_name='bookingdetails',
            name='carID',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='bookingdetails',
            name='trip_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 4, 17, 20, 50, 848719)),
        ),
    ]
