# Generated by Django 4.2.7 on 2024-02-04 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cab_booking', '0005_alter_bookingdetails_booking_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carsavailable',
            name='carNumber',
            field=models.TextField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='bookingdetails',
            name='booking_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 4, 17, 24, 13, 170701)),
        ),
        migrations.AlterField(
            model_name='bookingdetails',
            name='trip_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 4, 17, 24, 13, 170701)),
        ),
    ]
