# Generated by Django 4.2.7 on 2024-02-04 15:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cab_booking', '0009_alter_bookingdetails_booking_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availablecab',
            old_name='cabID',
            new_name='carID',
        ),
        migrations.AlterField(
            model_name='bookingdetails',
            name='booking_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 4, 20, 50, 58, 36363)),
        ),
        migrations.AlterField(
            model_name='bookingdetails',
            name='trip_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 4, 20, 50, 58, 36363)),
        ),
    ]
