# Generated by Django 4.2.7 on 2024-02-05 06:38

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cab_booking', '0017_alter_bookingdetails_booking_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='poolRideBooking',
            fields=[
                ('bookingID', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('carID', models.TextField(max_length=10)),
                ('start_location', models.TextField(max_length=50)),
                ('end_location', models.TextField(max_length=50)),
                ('booking_time', models.DateTimeField(default=datetime.datetime(2024, 2, 5, 12, 8, 17, 972200))),
                ('booking_fare_pu', models.IntegerField()),
                ('trip_date', models.DateField(default=datetime.datetime(2024, 2, 5, 12, 8, 17, 972200))),
                ('userID', models.IntegerField(default=0)),
                ('rideStatus', models.IntegerField(default=0)),
                ('seats_available', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='bookingdetails',
            name='booking_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 5, 12, 8, 17, 972200)),
        ),
        migrations.AlterField(
            model_name='bookingdetails',
            name='trip_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 5, 12, 8, 17, 972200)),
        ),
    ]
