# Generated by Django 4.2.7 on 2024-02-06 12:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cab_booking', '0021_alter_bookingdetails_booking_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poolridebooking',
            name='carCapacity',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='bookingdetails',
            name='booking_time',
            field=models.DateField(default=datetime.datetime(2024, 2, 6, 18, 19, 33, 157483)),
        ),
        migrations.AlterField(
            model_name='bookingdetails',
            name='trip_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 6, 18, 19, 33, 157483)),
        ),
        migrations.AlterField(
            model_name='poolridebooking',
            name='booking_time',
            field=models.DateField(default=datetime.datetime(2024, 2, 6, 18, 19, 33, 173151)),
        ),
        migrations.AlterField(
            model_name='poolridebooking',
            name='trip_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 6, 18, 19, 33, 173151)),
        ),
    ]
