# Generated by Django 4.2.7 on 2024-02-07 06:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cab_booking', '0022_poolridebooking_carcapacity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poolridebooking',
            old_name='seats_available',
            new_name='seats_booked',
        ),
        migrations.AlterField(
            model_name='bookingdetails',
            name='booking_time',
            field=models.DateField(default=datetime.datetime(2024, 2, 7, 11, 30, 18, 560911)),
        ),
        migrations.AlterField(
            model_name='bookingdetails',
            name='trip_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 7, 11, 30, 18, 560911)),
        ),
        migrations.AlterField(
            model_name='poolridebooking',
            name='booking_time',
            field=models.DateField(default=datetime.datetime(2024, 2, 7, 11, 30, 18, 560911)),
        ),
        migrations.AlterField(
            model_name='poolridebooking',
            name='trip_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 7, 11, 30, 18, 560911)),
        ),
    ]
