# Generated by Django 4.2.7 on 2024-02-05 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='searchTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ride_type', models.TextField(default='solo', max_length=50)),
                ('propose_fare', models.IntegerField(default=0)),
                ('pickup', models.TextField(default='Christ University,Pune', max_length=40)),
                ('drop', models.TextField(default='Pune Railway Station', max_length=40)),
                ('ride_date', models.DateField(default=datetime.datetime(2024, 2, 5, 15, 57, 41, 137165))),
            ],
        ),
    ]
